#ifndef SRC_AVR_SERVO_PREPROCESSOR_H
#define SRC_AVR_SERVO_PREPROCESSOR_H

#if F_CPU != 8000000L
#error This will work only for 8MHz CPU frequency
#endif

#define SERVO_PRESCALER 8
#define SERVO_TICKS_PER_MS ((uint16_t)(F_CPU / (SERVO_PRESCALER * (uint16_t)1000)))
#define SERVO_NEUTRAL_POSITION_TICKS ((3 * SERVO_TICKS_PER_MS) / 2)
#define SERVO_PERIOD_TICKS (SERVO_PERIOD * SERVO_TICKS_PER_MS)
#define SERVO_RANGE_TICKS SERVO_TICKS_PER_MS


#endif // SRC_AVR_SERVO_PREPROCESSOR_H
